### ISSUE TITLE
Bug when installing version above 0.0.3

### ISSUE THREAD

**Issue by frruit** [jackton1/django-clone#18]
Hi,
have following problem:
`
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wf63qX/django-clone/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wf63qX/django-clone/setup.py' fix "'"';f=getattr(tokenize, 'ur "'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-wf63qX/django-clone/
    Complete output (3 lines):moma
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-wf63qX/django-clone/setup.py'
    ----------------------------------------
[0m[91mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[0m[91mWARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[0mService 'cla_test' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

`

**Comment by jackton1** [comment]
This should be resolved.

Using `django-clone>=0.0.10`

**Comment by frruit** [comment]
And you have released it since 5 minutes :-)

**Comment by jackton1** [comment]
No worries.
