### ISSUE TITLE
Doesn't duplicate with custom `id`

### ISSUE THREAD

**Issue by gerbyzation** [jackton1/django-clone#9]
A model with a custom `id` field is not duplicated:

the `Branch` model has the id `id = models.UUIDField(primary_key=True, default=uuid4)`

```
>>> base_branch = Branch.objects.create(name='Main branch', parent=None, is_master=True, status=Branch.DRAFT)
>>> base_branch.pk
UUID('7a613f9d-90fe-4116-b897-69505cd4ff5c')
>>> clone = base_branch.make_clone()
>>> clone.pk
UUID('7a613f9d-90fe-4116-b897-69505cd4ff5c')
```

I think this is because the custom id shows up in `_meta.concrete_fields` the value is copied over, preventing it from generating a new PK. 

```
>>> base_branch._meta.concrete_fields
(<django.db.models.fields.UUIDField: id>, <django.db.models.fields.CharField: name>, <django.db.models.fields.BooleanField: is_master>, <django.db.models.fields.related.ForeignKey: parent>, <django.db.models.fields.CharField: status>)
```
The primary key field can be found through `instance._meta.pk`, filtering this out of the fields to copy should resolve this problem I think.

**Comment by jackton1** [comment]
@all-contributors please add @gerbyzation for bug, tests and code
